* ストレングス・ファインダーをやってみた
自分の才能を上から 5 つ見つけられるテストだそうです．[[../../../../wiki/reviews/さあ、才能(じぶん)に目覚めよう―あなたの5つの強みを見出し、活かす][さあ、才能(じぶん)に目覚めよう]]という本（ 1600 円）を買うと受検できます．面白かったので，皆さんも受けて，ぜひ結果を教えて下さい．

僕の結果は以下の通りでした．

** 最上志向
優秀であること、平均ではなく。これがあなたの基準です。平均以下の何かを平均より少し上に引き上げるには大変な努力を要し、あなたはそこに全く意味を見出しません。平均以上の何かを最高のものに高めるのも、同じように多大な努力を必要としますが、はるかに胸躍ります。自分自身のものか他の人のものかに関わらず、強みはあなたを魅了します。真珠を追い求めるダイバーのように、あなたは強みを示す明らかな徴候を探し求めます。生まれついての優秀さ、飲み込みの速さ、一気に上達した技能――これらがわずかでも見えることは、強みがあるかもしれないことを示す手がかりになります。そして一旦強みを発見すると、あなたはそれを伸ばし、磨きをかけ、優秀さへ高めずにはいられません。あなたは真珠を光り輝くまで磨くのです。このように、この自然に長所を見分ける力は、他の人から人を区別していると見られるかもしれません。あなたはあなたの強みを高く評価してくれる人たちと一緒に過ごすことを選びます。同じように、自分の強みを発見しそれを伸ばしてきたと思われる人たちに惹かれます。あなたは、あなたを型にはめて、弱点を克服させようとする人々を避ける傾向があります。あなたは自分の弱みを嘆きながら人生を送りたくありません。それよりも、持って生まれた天賦の才能を最大限に利用したいと考えます。その方が楽しく、実りも多いのです。そして意外なことに、その方がもっと大変なのです。

** 着想
あなたは着想に魅力を感じます。では、着想とは何でしょうか？　着想とは、ほとんどの出来事を最もうまく説明できる考え方です。あなたは複雑に見える表面の下に、なぜ物事はそうなっているかを説明する、的確で簡潔な考え方を発見すると嬉しくなります。着想とは結びつきです。あなたのような考え方を持つ人は、いつも結びつきを探しています。見た目には共通点のない現象が、何となく繋がりがありそうだと、あなたは好奇心をかき立てられるのです。着想とは、皆がなかなか解決できずにいる日常的な問題に対して、新しい見方をすることです。あなたは誰でも知っている世の中の事柄を取り上げ、それをひっくり返すことに非常に喜びを感じます。それによって人々は、その事柄を、変わっているけれど意外な角度から眺めることができます。あなたはこのような着想すべてが大好きです。なぜなら、それらは深い意味があるからです。なぜなら、それらは目新しいからです。それらは明瞭であり、逆説的であり、奇抜だからです。これらすべての理由で、あなたは新しい着想が生まれるたびに、エネルギーが電流のように走ります。他の人たちはあなたのことを、創造的とか独創的とか、あるいは概念的とか、知的とさえ名付けるかもしれません。おそらく、どれもあてはまるかもしれません。どれもあてはまらないかもしれません。確実なのは、着想はあなたにとってスリルがあるということです。そしてほとんど毎日そうであれば、あなたは幸せなのです。

** 親密性
親密性という資質は、あなたの人間関係に対する姿勢を説明します。 簡単に言えば、親密性という資質によって、あなたは既に知っている人々とより深い関係を結ぶ方向に引き寄せられます。あなたは必ずしも未知の人たちと出会うことを避けているわけではありません――事実、知らない人と友人になるスリルを楽しむような他の資質を、あなたは持っているかもしれないのです――しかし、あなたは親しい友人のそばにいてこそ、大きな喜びと力を得るのです。あなたは親密であることに心地よさを感じます。一旦最初の関係ができあがると、あなたは積極的にその関係をさらに深めようとします。あなたは彼らの感情、目標、不安、夢を深く理解したいと思っています。そして、彼らにもあなたを深く理解してもらいたいと願っています。あなたは、このような親密さがある程度の危険性を含んでいることを知っています――あなたは利用されるかもしれないのです――しかし、あなたはその危険性を解かった上で受け入れます。あなたにとって人間関係は、それが本物である時のみ価値を持ちます。そして、それが本物であるかどうかを知る唯一の方法は、相手に身を委ねることです。互いの気持ちを共有すればする程、お互いの危険性も大きくなります。お互いの危険性が大きくなればなる程、自分たちの意思が本物であることを、よりはっきりと証明できるのです。これらが真の友情を築き上げるための一つひとつのステップであり、あなたはそのステップを喜んで進んで行きます。

** 戦略性
戦略性という資質によって、あなたはいろいろなものが乱雑にある中から、最終の目的に合った最善の道筋を発見することができます。これは学習できるスキルではありません。これは特異な考え方であり、物事に対する特殊な見方です。他の人には単に複雑さとしか見えない時でも、あなたにはこの資質によってパターンが見えます。これらを意識して、あなたはあらゆる選択肢のシナリオの最後まで想像し、常に「こうなったらどうなる？　では、こうなったらどうなる？」と自問します。このような繰り返しによって、先を読むことができるのです。そして、あなたは起こる可能性のある障害の危険性を正確に予測することができます。それぞれの道筋の先にある状況が解かることで、あなたは道筋を選び始めます。行き止まりの道をあなたは切り捨てます。まともに抵抗を受ける道を排除します。混乱に巻き込まれる道を捨て去ります。そして、選ばれた道――すなわちあなたの戦略――にたどり着くまで、あなたは選択と切り捨てを繰り返します。そしてこの戦略を武器として先へ進みます。これが、あなたの戦略性という資質の役割です：問いかけ、選抜し、行動するのです。

** 学習欲
あなたは学ぶことが大好きです。あなたが最も関心を持つテーマは、あなたの他の資質や経験によって決まりますが、それが何であれ、あなたはいつも学ぶ「プロセス」に心を惹かれます。内容や結果よりもプロセスこそが、あなたにとっては刺激的なのです。あなたは何も知らない状態から能力を備えた状態に、着実で計画的なプロセスを経て移行することで活気づけられます。最初にいくつかの事実に接することでぞくぞくし、早い段階で学んだことを復誦し練習する努力をし、スキルを習得するにつれ自信が強まる――これがあなたの心を惹きつける学習プロセスです。あなたの意欲の高まりは、あなたに社会人学習――外国語、ヨガ、大学院など――への参加を促すようになります。それは、短期プロジェクトへの取組みを依頼されて、短期間で沢山の新しいことを学ぶことが求められ、そしてすぐにまた次の新しいプロジェクトへに取組んでいく必要のあるような、活気に溢れた職場環境の中で力を発揮します。この「学習欲」という資質は、必ずしもあなたがその分野の専門家になろうとしているとか、専門的あるいは学術的な資格に伴う尊敬の念を求めていることを意味するわけではありません。学習の成果は、「学習のプロセス」ほど重要ではないのです。
