language: ruby
sudo: required
dist: trusty

env:
  global:
    - PAGES=$(mktemp --directory --tmpdir=`pwd`)
    - PAGES_BASENAME=$(basename $PAGES)
servicies:
  - docker

before_install:
  - docker pull niku/nwiki

script:
  # `>-` indicates folding lines(even without backslash)
  - >-
    docker run
    -e "LANG=C.UTF-8"
    -e "NWIKI_SITE_NAME=ヽ（´・肉・｀）ノログ"
    -e "NWIKI_TAGLINE=How do we fight without fighting?"
    -e "NWIKI_ENDPOINT=http://niku.name/"
    -e "NWIKI_GA_TRACKING_ID=UA-26456277-1"
    -v `pwd`:/app/repo
    -v $PAGES:/app/pages
    niku/nwiki rake nwiki:run

deploy:
  provider: pages
  # local-dir must be relative path to the current directory.
  # https://docs.travis-ci.com/user/deployment/pages/#Further-configuration
  local-dir: $PAGES_BASENAME
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  repo: niku/niku.github.io
  target_branch: master
