* サッポロビームを4年ほぼ毎週開催して約200回やりどうなっているか
サッポロビームをふりかえり，どのように続けているか，続けていて今どうなっているかを確認する．

サッポロビームはだいたい毎週木曜日にやっている ErlangVM(BEAM) に載っている言語に関する話題やそうでない話題でわいわいやる集まりだ．
どのくらいだいたいかというと，2014 年 02 月 13 日に 1 回目を開催，2017 年 12 月 06 日に 196 回目を開催した．

#+begin_src elixir
Date.diff(~D[2017-12-06], ~D[2014-02-13]) / 7
# => 198.85714285714286
#+end_src

もし毎週やっているとこの時点で 199 回開催していたことになる．実際には 196 回なので

#+begin_src elixir
196 / 199
# => 0.9849246231155779
#+end_src

開催率 98.5% の，4 年間だいたい毎週だ．

** モチベーション
なぜ最初にはじめてみようと思ったのか当初のモチベーションを書き出してみる．
もちろん現在のサッポロビームは誰のものでもなく，主旨に賛同してくれる人なら誰が開催してもいい集まりだ．

大きく2つ，何かへ集まり続けることへの興味と，テクノロジ ErlangVM(BEAM) への興味があった．

*** 集まり続けることへの興味
札幌ではたくさんの勉強会が産まれ盛り上がりそして休眠するのをまのあたりにしていた．
楽しかったのに残念だった．なぜ休眠するのか．もっと簡単に軽く（ Light Weight に）できれば続くのではないか？
という観点から，集まるのを簡単にすると続くだろうか，その場合楽しさには影響はないか，集まるのを簡単にするためにどのようにすればいいだろうか．

といった，集まり方自体の改良を私が試す場所を用意したかった．

*** テクノロジへの興味
アクターモデルを持つと言われている ErlangVM についてよく知りたかった．
そもそもアクターモデルのことを文章で読んでも全然わからなかったので，使いながら覚えられるとありがたい．
独りだとくじけそうなので，だれかと悩みを共有しながら進められると続けられるかもしれないと考えていた．

ムーアの法則の終わりがみえてきた昨今，
これまでのようにハードウェアの進化によってソフトウェアがこのまま単に速くなる時代ではなくなりそうで，
複数のCPUコア，複数のマシンをプログラマが辛くない気持で使えるような言語/フレームワークが近い将来広まりそうな気がする．
今のうちにそういった界隈で有名になっておき，お金を稼ごうと考えていた．

** 集まり続ける観点からのサッポロビーム
私は，意義の有無にかかわらず，苦しいことを長い時間続けるのは人より苦手だと感じている．
そのために日々の運営が苦しくならないような，運営のやり方というのを模索してきた．

*** はじめるのがしんどい
集まり続けるためには，まずはじめなければいけないが，はじめることが心理的に重かったりする．

心理的な重さの一つは「きちんとしたい」という気持ではないだろうか．
その気持ちは成長には大事だと思うし尊重するが，
こと勉強会においてはきちんとしたいから始められないより，
きちんとしなくても始められる方が誰にとってもいい事が多いように思う．

私は一人でもくもくと勉強してみるという試みを何週間か試し，
続けられそうな気がしたので，そのままサッポロビームという名前を名乗ることにした．

*** 会場予約が大変，属人化する
開催頻度が高いと会場の予約や確保も大変だ．

予約 = 約束と考えると，趣味の集まりにわざわざ約束をして心理的重みを自ら作りだしていくのはできれば避けたい．
また，参加者のご厚意で会議室を使わせてもらえるといった打診も受けたことがあるが，辞退させていただいている．

なぜかというと，利用させていただける便利さより，その会場が都合つかなくなったときの調整の面倒さが勝っていると感じられるためだ．
利便性より安定性を採用しているとも言える．

以上の理由から，サッポロビームは予約が必要なく，お金を払えば誰でも居ることができるスターバックスの隅で迷惑にならないように開催している．

*** 告知や連絡が大変
参加者への開催告知が毎回となるとなかなか面倒だったりする．

私は採用していないのだが，告知や連絡を *しない* というのも一つの手だと思う．

私の場合は使い慣れているツールで代用することにした．
github の issue を使って毎回告知，twitter で拡散，github の issue のコメントで記録している．
普段やっていることと乖離が少ないので楽に行えている．

*** 外部の人が成果や雰囲気を知る術がない
記録を残しておくと，普段どんなことをしている会なのか，参加していない人が雰囲気を掴み，参加しやすくなるのに役立つ．

そこで集まりの最後に，参加者へ「やったことを github の issue にコメントしてもらえると僕が嬉しいなあ」と伝えてまわっている．

みんなから聞きとり，まとめの文章を書くのは，私の性格的に続かないだろうという読みがあり，このような形式をとっている．

*** いつやめてもいいと割り切る
逆説的だが，いつやめてもいいという気持を持っておくことは，心理的な負担を軽減し，長く会を続けるための助けになっているように思う．

やめやすくすることで，始めやすくかつ続けやすくするというのは Joel on Software という優れたエッセイの中にある [[http://japanese.joelonsoftware.com/Articles/StrategyLetterIII.html][ストラテジーレターⅢ: もとに戻してくれ!]] にヒントを得ている．

** 集まってたらどうなった？
客観的に評価できそうなものをいくつか列挙する．

- だいたい毎回何人か来てくれて，ErlangVM 関連の話ができるようになった
- 知識ゼロから始めて [[https://github.com/niku/hobot][プラガブルな Bot フレームワーク]] を始めとするライブラリを作ることができるようになった
- OpenAPI(Swagger) の README に [[https://github.com/swagger-api/swagger-codegen/blob/v2.2.3/README.md#template-creator][Elixir クライアント作者]] として名前が載った
- Ruby札幌と共同で RubySapporo.beam というイベントを不定期に開催して楽しい時間を過ごせるようになった
  - [[https://rubysapporo.doorkeeper.jp/events/50956][#1]]
  - [[https://rubysapporo.doorkeeper.jp/events/57253][#2]]
  - [[https://rubysapporo.doorkeeper.jp/events/65693][#3]]
- [[http://amzn.to/2As1SfU][プログラミングElixir]] という本のレビュアーにお誘いいただき，レビューに参加させていただいた
- [[https://codezine.jp/article/detail/10071][Elixir Conf Japan 2017 のレポート]] を書かないかとお誘いいただいた
- るびまで [[http://magazine.rubyist.net/?0056-naruhodo_erlang_process][なるほど Erlang プロセス]] という記事を掲載していただいた

4 年間ほぼ毎週続けているということに自分ごとながら驚くものの，4 年間やったわりには，それほど成果というものは出ていないところが今後の課題である．

このくらいできていたらまあまあ凄いという評価のしかたもあるので，どちらを採用するのかは，迷っている．

** 最後に
ErlangVM 全然わからんというところから始めて，多少わかるようになったのはすごく楽しかった．

一方で集まり続けるという観点では，安定しており，気持が萎えるまで無限にこの形式で続けられそうな気がしてきたので，
ここから運営をどうするか，私がどのようにサッポロビームにかかわるかは（このまま変わらず続けるという選択肢も込みで）再考するべき段階にきたと思う．

私が国語の教科書で読んだ，印象に残っている『[[http://amzn.to/2B48gtx][加代の四季 雪]]』という杉みき子作の詩がある．

#+begin_quote
ちらちらとふる雪は、ぬれた地面に落ちて、ジュッともいわないで消えていく。
その上に落ちてくる雪も、またその次に来る雪も、みんな見るまに解けてしまって、いっこうに積もりそうもない。
（中略）
あんなに、つもってはきえ、つもってはきえしているのに、どうして、いつのまに、ふんでもとけないあつい雪の道ができるんだろう。
土にとりついて、とけないで、上からおちてくるなかまをささえた、そのさいしょのひとつぶの雪を、加代は見たい。
#+end_quote

土にとりついて，とけないで，上からおちてくるなかまをささえた，そのさいしょのひとつぶの雪に私はなってみたいと思ったのだった．
なれているだろうか．なれているといいなあ．
